export const HOUSE_SPACES = {
    ATTIC: 'attic',
    AUX_ROOM: 'auxRoom',
    CORRIDOR: 'corridor',
    DINNING: 'dinning',
    ENTRANCE: 'entrance',
    FRONT_1: 'front1',
    GARAGE: 'garage',
    GARDEN_1: 'garden1',
    GARDEN_2: 'garden2',
    GARDEN_3: 'garden3',
    GARDEN_4: 'garden4',
    GARDEN_5: 'garden5',
    KITCHEN: 'kitchen',
    LAUNDRY: 'laundry',
    LIVING: 'living',
    MAIN_BATHROOM: 'mainBathroom',
    MAIN_CLOSET: 'mainCloset',
    MAIN_ROOM: 'mainRoom',
    PARK: 'park',
    ROOM_2: 'room2',
    ROOM_2_BATHROOM: 'room2Bathroom',
    ROOM_3: 'room3',
    ROOM_3_BATHROOM: 'room3Bathroom',
    STUDY: 'study',
    TERRACE: 'terrace',
    TV_ROOM: 'tvRoom'
}
